# Generated by Django 5.2.1 on 2025-05-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_company_location_application_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.PositiveIntegerField(),
        ),
    ]
